webapp:
  image: nginx:alpine
  volumes:
    - ../:/app/
    - ./vhosts/:/etc/nginx/conf.d/
  restart: on-failure:5
webapp_php:
  image: advice/php:5.6
  working_dir: /app/
  environment:
    APP_ENV: development
  volumes:
    - ../:/app/
